grammar com.xkp.codexcess.Xss with org.eclipse.xtext.common.Terminals

generate xss "http://www.xkp.com/codexcess/Xss"

Program
	:	block=Block
	;

Block
	:	'{' StmList? '}'
	;

StmList
	:	Statement+
	;

Statement
	:	LocalVarDecl ';'
	|	Block
	;

LocalVarDecl
	:	Type VariableDeclarator
	;

VariableDeclarator
	:	IDENTIFIER ('=' Expression)?
	;

//------------------------------------------------- Expressions
ExpressionOpt
	:	Expression?
	;

ExpressionList
	:	Expression (',' Expression)*
	;

Expression
	:	ConditionalExpr (('='|'+='|'-='|'*='|'/='|'<<='|'>>=') ConditionalExpr)*
	;

ConditionalExpr
	:	OrExpr ('?' OrExpr ':' ConditionalExpr)?
	;

OrExpr
	:	AndExpr ('||' AndExpr)*
	;

AndExpr
	:	EqualityExpr ('&&' EqualityExpr)*
	;

EqualityExpr
	:	CompExpr (('=='|'!=') CompExpr)*
	;

CompExpr
	:	ShiftExpr (('<'|'>'|'<='|'>='|'as'|'is'|'has') ShiftExpr)*
	;

ShiftExpr
	:	AddExpr (('<<'|'>>') AddExpr)*
	;

AddExpr
	:	MultExpr (('+'|'-') MultExpr)*
	;

MultExpr
	:	UnaryExpr (('*'|'/'|'%') UnaryExpr)*
	;

//check this
UnaryExpr
	:	'!' MethodExpr
	|	'-' MethodExpr
	|	'++' MethodExpr
	|	'--' MethodExpr
	|	MethodExpr
	;

MethodExpr
	//:	Method (Method | PrimaryExpr)*
	//|	PrimaryExpr
	:	PrimaryExpr+
	;

Method
	:	MEMBER_NAME ( '(' ArgListOpt ')' )?
	|	'[' ExpressionList ']'
	//|	'++'
	//|	'--'
	;

ObjectListOpt
	:	ObjectList?
	;

ObjectList
	:	ObjectValue (',' ObjectValue)*;

ObjectValue
	:	IDENTIFIER ':' Expression
	;

PrimaryExpr
	:	Primary
	|	'new' Type '(' ArgListOpt ')'
	|	'{' ObjectListOpt '}'
	//|	'(' Expression ')'
	;

ArrayLiteral
	:	'[' ArgListOpt ']'
	;

Primary
	:	IDENTIFIER ( '(' ArgListOpt ')' )?
	|	ArrayLiteral
	|	Literal
	;

//------------------------------------------------- Arguments
ArgListOpt
	:	ArgList?
	;

ArgList
	:	Argument (',' Argument)*
	;

Argument
	//:	(IDENTIFIER '=' ConditionalExpr)
	//|	ConditionalExpr
	:	IDENTIFIER
	;

//------------------------------------------------- Types
Type
	:	IDENTIFIER ('<' TypeArgList '>')?
	;

TypeArgList
	:	TypeArgument (',' TypeArgument)*
	;

TypeArgument
	:	IDENTIFIER '=' PrimaryExpr
	|	PrimaryExpr
	;

//------------------------------------------------- Literals
Literal
	:	'true'
	|	'false'
	|	DEC_LITERAL
	|	HEX_LITERAL
	|	REAL_LITERAL
	|	CHAR_LITERAL
	|	STRING_LITERAL
	|	'null'
	;

//------------------------------------------------- IDs
MemberList:
	MEMBER_NAME+
;

QualifiedID:
  	IDENTIFIER MemberList?
;

terminal IDENTIFIER: ('a'..'z'|'A'..'Z') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
terminal MEMBER_NAME: '.' ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
terminal REAL_LITERAL: ('0'..'9')* '.' INT;
terminal DEC_LITERAL: INT;
terminal HEX_LITERAL: '0' ('x'|'X') ('0'..'9'|'A'..'F'|'a'..'f')+;
terminal STRING_LITERAL: STRING;
terminal CHAR_LITERAL:
		"'" ( '\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|"'") ) "'"
	;
