grammar com.xkp.codexcess.Xss hidden(WS, ML_COMMENT, SL_COMMENT)
											
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

generate xss "http://www.xkp.com/codexcess/Xss"

Program
	:	block=Block
	;

Block
	:	'{' StmList? '}'
	;

StmList
	:	Statement+
	;

Statement
	:	LocalVarDecl ';'
	|	Block
	;

LocalVarDecl
	:	Type VariableDeclarator
	;

VariableDeclarator
	:	IDENTIFIER ('=' Expression)?
	;

//------------------------------------------------- Expressions
ExpressionOpt
	:	Expression?
	;

ExpressionList
	:	Expression (',' Expression)*
	;

Expression
	:	ConditionalExpr (('='|'+='|'-='|'*='|'/='|'<<='|'>>=') ConditionalExpr)*
	;

ConditionalExpr
	:	OrExpr ('?' OrExpr ':' ConditionalExpr)?
	;

OrExpr
	:	AndExpr ('||' AndExpr)*
	;

AndExpr
	:	EqualityExpr ('&&' EqualityExpr)*
	;

EqualityExpr
	:	CompExpr (('=='|'!=') CompExpr)*
	;

CompExpr
	:	ShiftExpr (('<'|'>'|'<='|'>='|'as'|'is'|'has') ShiftExpr)*
	;

ShiftExpr
	:	AddExpr (('<<'|'>>') AddExpr)*
	;

AddExpr
	:	MultExpr (('+'|'-') MultExpr)*
	;

MultExpr
	:	UnaryExpr (('*'|'/'|'%') UnaryExpr)*
	;

//check this
UnaryExpr
	:	'!' MethodExpr
	|	'-' MethodExpr
	|	'++' MethodExpr
	|	'--' MethodExpr
	|	MethodExpr
	;

MethodExpr
	:	Method* PrimaryExpr
	;

Method
	:	MEMBER_NAME ( '(' ArgListOpt ')' )?
	|	'[' ExpressionList ']'
	//|	('++'|'--')
	;

ObjectListOpt
	:	ObjectList?
	;

ObjectList
	:	ObjectValue (',' ObjectValue)*;

ObjectValue
	:	IDENTIFIER ':' Expression
	;

PrimaryExpr
	:	('(' Expression ')')
	|	Primary
	|	'new' Type '(' ArgListOpt ')'
	|	'{' ObjectListOpt '}'
	;

ArrayLiteral
	:	'[' ArgListOpt ']'
	;

Primary
	:	IDENTIFIER ( '(' ArgListOpt ')' )?
	|	ArrayLiteral
	|	Literal
	;

//------------------------------------------------- Arguments
ArgListOpt
	:	ArgList?
	;

ArgList
	:	Argument (',' Argument)*
	;

Argument
	//:	(IDENTIFIER '=' ConditionalExpr)
	//|	ConditionalExpr
	:	IDENTIFIER
	;

//------------------------------------------------- Types
Type
	:	IDENTIFIER ('<' TypeArgList '>')?
	;

TypeArgList
	:	TypeArgument (',' TypeArgument)*
	;

TypeArgument
	:	IDENTIFIER '=' PrimaryExpr
	|	PrimaryExpr
	;

//------------------------------------------------- Literals
Literal
	:	'true'
	|	'false'
	|	DEC_LITERAL
	|	HEX_LITERAL
	|	REAL_LITERAL
	|	CHAR_LITERAL
	|	STRING_LITERAL
	|	'null'
	;

//------------------------------------------------- IDs
MemberList
	:	MEMBER_NAME+
	;

QualifiedID
	:	IDENTIFIER MemberList?
	;

terminal IDENTIFIER: ('a'..'z'|'A'..'Z') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
terminal MEMBER_NAME: '.' ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
terminal REAL_LITERAL: ('0'..'9')* '.' DEC_LITERAL;
terminal DEC_LITERAL returns ecore::EInt: ('0'..'9')+;
terminal HEX_LITERAL: '0' ('x'|'X') ('0'..'9'|'A'..'F'|'a'..'f')+;
terminal CHAR_LITERAL:
		"'" ( '\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|"'") ) "'"
	;
terminal STRING_LITERAL: 
			'"' ( '\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|'"') )* '"' |
			"'" ( '\\' ('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|"'") )* "'"
		; 

terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
terminal ML_COMMENT	: '/*' -> '*/';
terminal SL_COMMENT 	: '//' !('\n'|'\r')* ('\r'? '\n')?;

terminal WS			: (' '|'\t'|'\r'|'\n')+;

terminal ANY_OTHER: .;
